
spring:
  messages:
    #设置国际化资源文件的位置
    basename: i18n/login
  thymeleaf:
    #禁用缓存
    cache: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    password: 1234
    username: root
    url: jdbc:mysql://localhost:3306/zj
#    password: 123456
#    username: test
#    url: jdbc:mysql://172.16.105.232:3306/olzh?useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver

 #引入druid数据源
  profiles:
    active: druid
  redis:
    database: 0
    host: localhost
    port: 6379
    pool:
      max-active: 8
      max-wait: 1
      max-idle: 8
      min-idle: 0
    timeout: 0
  data:
    mongodb:
      database: hello
      authentication-database: admin
      uri: mongodb://localhost:27017
server:
  port: 8080
mybatis:
  #config-location: classpath:com/conf/mybatisConfig.xml(用配置类代替--MybatisConfig类)
  mapper-locations: classpath:com/model/mapper/*Sql.xml

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
logging:
  level:
   com.model: debug


