
spring:
  messages:
    #设置国际化资源文件的位置
    basename: i18n/login
  thymeleaf:
    #禁用缓存
    cache: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    password: 1234
    username: root
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver
 #引入druid数据源
  profiles:
    active: druid
server:
  port: 8080
